// <auto-generated />
using System;
using FarmacorpPOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmacorpPOS.Infrastructure.Migrations
{
    [DbContext(typeof(FarmacorpDbContext))]
    partial class FarmacorpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdCategoriaPadre")
                        .HasColumnType("int");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdCategoriaPadre");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.CodigoBarra", b =>
                {
                    b.Property<int>("IdCodigoBarra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCodigoBarra"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("UniqueCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCodigoBarra");

                    b.HasIndex("IdProducto");

                    b.HasIndex("UniqueCodigo")
                        .IsUnique();

                    b.ToTable("CodigoBarra", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.ErpProducto", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UniqueCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProducto");

                    b.HasIndex("UniqueCodigo")
                        .IsUnique();

                    b.ToTable("ErpProducto", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.ExpProducto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoProducto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdTipoProducto");

                    b.ToTable("ExpProducto", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.ProductoCategoria", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductoCategoria", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.TipoProducto", b =>
                {
                    b.Property<int>("IdTipoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoProducto");

                    b.ToTable("TipoProducto", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoProducto = 1,
                            Descripcion = "Medicamento"
                        },
                        new
                        {
                            IdTipoProducto = 2,
                            Descripcion = "Cosmético"
                        },
                        new
                        {
                            IdTipoProducto = 3,
                            Descripcion = "Higiene"
                        },
                        new
                        {
                            IdTipoProducto = 4,
                            Descripcion = "Suplemento"
                        });
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.VentaExpress", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UniqueCodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdProducto");

                    b.ToTable("VentaExpress", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.Entities.Categoria", "CategoriaPadre")
                        .WithMany("CategoriasHijas")
                        .HasForeignKey("IdCategoriaPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.CodigoBarra", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.Entities.ExpProducto", "Producto")
                        .WithMany("CodigosBarra")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.ErpProducto", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.Entities.ExpProducto", "Producto")
                        .WithOne("ErpProducto")
                        .HasForeignKey("FarmacorpPOS.Domain.Entities.ErpProducto", "IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.ExpProducto", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.Entities.TipoProducto", "TipoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("IdTipoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.ProductoCategoria", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmacorpPOS.Domain.Entities.ExpProducto", "Producto")
                        .WithMany("Categorias")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.VentaExpress", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.Entities.ExpProducto", "Producto")
                        .WithMany("Ventas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("CategoriasHijas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.ExpProducto", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("CodigosBarra");

                    b.Navigation("ErpProducto");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Entities.TipoProducto", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
